- name: Configure BGP Global
  hosts: routers
  gather_facts: false
  vars_files: bgp_global.cfg

  tasks:
    - name: Use BGP Global resource module [Cisco IOS]
      cisco.ios.ios_bgp_global:
        state: purged
        config: "{{ cfg }}"
      when: ansible_network_os == 'cisco.ios.ios'

    - name: Use BGP Global resource module [Cisco NX-OS]
      cisco.nxos.nxos_bgp_global:
        state: purged
        config: "{{ cfg }}"
      when: ansible_network_os == 'cisco.nxos.nxos'

    - name: Use BGP Global resource module [Cisco IOS XR]
      cisco.iosxr.iosxr_bgp_global:
        state: purged
        config: "{{ cfg }}"
      when: ansible_network_os == 'cisco.iosxr.iosxr'
